language: cpp

sudo: false

compiler:
- clang

addons:
  apt:
    packages:
    - libboost-dev
    - libgdal-dev
    - libgeotiff-dev
    - libboost-graph-dev
    - libqt4-dev
    - libqtcore4
    - libqtgui4
    - libopencv-dev
    - libtinyxml-dev
    - libopenthreads-dev
    - libfftw3-dev

before_script:
  - export SOURCE_DIR=$PWD
  - cd /tmp
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.tar.gz --no-check-certificate
  - tar -xzf cmake-3.4.0-rc3-Linux-x86_64.tar.gz
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip --no-check-certificate
  - unzip ninja-linux.zip
  - echo $SOURCE_DIR
  - cd $SOURCE_DIR
  - mkdir build
  - cd build

script: /tmp/cmake-3.4.0-rc3-Linux-x86_64/bin/cmake ../SuperBuild -DCMAKE_MAKE_PROGRAM=/tmp/ninja -DCMAKE_INSTALL_PREFIX=../install -DUSE_SYSTEM_TIFF=ON -DUSE_SYSTEM_ZLIB=ON -DUSE_SYSTEM_GEOTIFF=ON -DUSE_SYSTEM_JPEG=ON -DUSE_SYSTEM_SQLITE=ON -DUSE_SYSTEM_CURL=ON -DUSE_SYSTEM_PNG=ON -DUSE_SYSTEM_OPENCV=ON -DUSE_SYSTEM_QT4=ON -DUSE_SYSTEM_GEOS=ON -DUSE_SYSTEM_FFTW=ON -DUSE_SYSTEM_PROJ=ON -DUSE_SYSTEM_EXPAT=ON -DUSE_SYSTEM_BOOST=ON -DUSE_SYSTEM_LIBKML=ON -DUSE_SYSTEM_TINYXML=ON -DUSE_SYSTEM_OPENJPEG=ON -DUSE_SYSTEM_OPENTHREADS=ON -DUSE_SYSTEM_GDAL=ON -DUSE_SYSTEM_ITK=OFF -DUSE_SYSTEM_MUPARSER=ON -DUSE_SYSTEM_MUPARSERX=OFF -DUSE_SYSTEM_OSSIM=OFF -DOTB_USE_OPENJPEG=OFF -DOTB_USE_MUPARSER=OFF -DOTB_USE_MUPARSERX=OFF -G "Ninja" && /tmp/ninja
