language: cpp

sudo: false

compiler:
- clang

addons:
  apt:
    packages:
    - cmake
    - libboost-dev
    - libgdal-dev
    - libgeotiff-dev
    - libboost-graph-dev
    - libqt4-dev
    - libqtcore4
    - libqtgui4
    - libopencv-dev
    - libtinyxml-dev
    - libopenthreads-dev
    - libfftw3-dev
    - ninja-build

before_script:
- mkdir build
- cd build

script: cmake ../SuperBuild -DCMAKE_INSTALL_PREFIX=../install -DUSE_SYSTEM_TIFF=ON -DUSE_SYSTEM_ZLIB=ON -DUSE_SYSTEM_GEOTIFF=ON -DUSE_SYSTEM_JPEG=ON -DUSE_SYSTEM_SQLITE=ON -DUSE_SYSTEM_CURL=ON -DUSE_SYSTEM_PNG=ON -DUSE_SYSTEM_OPENCV=ON -DUSE_SYSTEM_QT4=ON -DUSE_SYSTEM_GEOS=ON -DUSE_SYSTEM_FFTW=ON -DUSE_SYSTEM_PROJ=ON -DUSE_SYSTEM_EXPAT=ON -DUSE_SYSTEM_BOOST=ON -DUSE_SYSTEM_LIBKML=ON -DUSE_SYSTEM_TINYXML=ON -DUSE_SYSTEM_OPENJPEG=ON -DUSE_SYSTEM_OPENTHREADS=ON -DUSE_SYSTEM_GDAL=ON -DUSE_SYSTEM_ITK=OFF -DUSE_SYSTEM_MUPARSER=ON -DUSE_SYSTEM_MUPARSERX=OFF -DUSE_SYSTEM_OSSIM=OFF -DOTB_USE_OPENJPEG=OFF -DOTB_USE_MUPARSER=OFF -DOTB_USE_MUPARSERX=OFF -G "Ninja" && ninja-build
