language: cpp

compiler:
- clang

before_script:
- mkdir build
- cd build
- sudo apt-get update -qq
- sudo apt-get install boost-devel libgdal-dev (>= 1.10.0) libgeotiff-dev libboost-graph-dev libqt4-dev libqtcore4 libqtgui4 libopencv-dev libossim-dev libinsighttoolkit4-dev libtinyxml-dev

script: cmake -DCMAKE_INSTALL_PREFIX=../install .. && make